// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufltukmwksudhewtctxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbHR1a213a3N1ZGhld3RjdHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTEwNTUsImV4cCI6MjA2NTc2NzA1NX0.hBAAbQ_kHRNMnv-C2diLGudZXyXvrBcHujXASreA6_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);